# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Bump Version

on: workflow_dispatch

jobs:
  bump-version:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: git config --global user.email heemomile@gmail.com
    - run: git config --global user.name heemomile
    
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://npm.pkg.github.com'
        
    - name: npm version up
      run: npm version patch
      
    - name: git push master
      run: git push origin master --tags
    - name: git push develop
      run: git push origin develop --tags
    - uses: actions/upload-artifact@v2
      with:
        name: src
        path: ./
